matn = input("Matn kiriting: ")
matn = matn.replace("a", "0")
matn = matn.replace("b", "1")
matn = matn.replace("c", "2")
matn = matn.replace("d", "3")
matn = matn.replace("e", "4")
matn = matn.replace("f", "5")
matn = matn.replace("g", "6")
matn = matn.replace("h", "7")
matn = matn.replace("i", "8")
matn = matn.replace("j", "9")
matn = matn.replace("k", "!")
matn = matn.replace("l", "@")
matn = matn.replace("m", "#")
matn = matn.replace("n", "$")
matn = matn.replace("o", "%")
matn = matn.replace("p", "^")
matn = matn.replace("q", "&")
matn = matn.replace("r", "*")
matn = matn.replace("s", "(")
matn = matn.replace("t", ")")
matn = matn.replace("u", "-")
matn = matn.replace("v", "=")
matn = matn.replace("w", "_")
matn = matn.replace("x", "+")
matn = matn.replace("y", "'")
matn = matn.replace("z", "\\")

print(f"Shifrlangan matn: {matn}")