print(1)
print(1,2)
print(1+4)
print('bir' + ' ikki')
print('bir', ' ikki')
print("PC")
print("""Ko'p qatorli 
matn""")
print("\" - qo'shtirnoq")
print('" - qo\'shtirnoq')
print("' - birtirnoq")
print('\' - birtirnoq')
print('Birinchi qator\nIkkinchi qator')
print('Birinchi ustun\t\tIkkinchi ustun')
